safe:        false
auto:        true 
server:      true
server_port: 4000
baseurl:    /
url: http://esc.so
title:      笔记整理

source:      .
destination: ./_site
plugins:     ./_plugins

exclude:
- template.html

markdown:    maruku
permalink:   /:categories/:year/:month/:title.html

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
